# Default values for urs-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

connector_main:
  enabled: true
  name: connector-main
  image: "codegb/urs-connector-main"
  root:
    port: 8080
  cassandra:
    keyspace_name: ""
    contact_point: 127.0.0.1
    port: 9042
    username: ""
    local_datacenter: ""
  datasource:
    url: ""
    username: ""
    console:
      enabled: true
  zookeeper:
    host: 127.0.0.1
    port: 2181
    range:
      limit: 1000000
    znode:
      path:
        counter: "/counter"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    httpGet:
      path: /health
      port: 8080
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    httpGet:
      path: /system/health
      port: 8080
  secret:
    name: connector-main-secret
    cassandra_password: password
    datasource_password: password

common:
  image_pull_policy: Always
  memory:
    microservices: "512M"

cassandra:
  enabled: true

zookeeper:
  enabled: true
